FROM python:3.13-slim

RUN pip install --no-cache-dir mkdocs==1.6.1 \
    && mkdir -p /workspace \
    && chown 65532:65532 /workspace

USER 65532:65532
WORKDIR /workspace
ENTRYPOINT ["mkdocs"]
CMD ["serve", "--dev-addr=0.0.0.0:8000"]
