FROM rust:1.98-slim-bookworm@sha256:ff521445a372125ed4f76e1453a1f8098f2d05332d1601d30db1c1f62757e730
RUN apt-get update && apt-get install -y --no-install-recommends \
    libtss2-dev libssl-dev pkg-config python3 swtpm swtpm-tools tpm2-tools \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /src
RUN rustup component add rustfmt --toolchain 1.98.1
