FROM python:3.13-alpine@sha256:399babc8b49529dabfd9c922f2b5eea81d611e4512e3ed250d75bd2e7683f4b0

RUN pip install --no-cache-dir mkdocs==1.6.1 \
    && mkdir -p /workspace \
    && chown 65532:65532 /workspace

USER 65532:65532
WORKDIR /workspace
ENTRYPOINT ["mkdocs"]
CMD ["serve", "--dev-addr=0.0.0.0:8000"]
