FROM rust:1.98-bookworm@sha256:93ce27a88655056a51dbdd8f5f2d7ddc071c7b0070fb288a37b5a285fc83971e
RUN apt-get update && apt-get install -y --no-install-recommends \
    libtss2-dev libssl-dev pkg-config swtpm swtpm-tools tpm2-tools \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /src
RUN rustup component add rustfmt --toolchain 1.98.1
