// The checked-in bundle is served directly; Node is only needed to rebuild it.
import {build} from "esbuild";
import {readFile, writeFile, rename} from "node:fs/promises";
import {fileURLToPath} from "node:url";
import path from "node:path";

const root = path.dirname(fileURLToPath(import.meta.url));
const result = await build({
  absWorkingDir: root, entryPoints: ["editor-src/controller.js"], bundle: true,
  format: "iife", target: ["es2022"], minify: true, write: false,
  supported: {"template-literal": false},
  legalComments: "inline", banner: {js: "// Generated by npm --prefix web run build. Sources: web/editor-src/. Licenses: web/editor.LICENSE."}
});
const bundle = result.outputFiles[0].text;
if (Buffer.byteLength(bundle) > 1024 * 1024) throw new Error("Editor exceeds the server's 1 MiB asset limit");
const lock = JSON.parse(await readFile(path.join(root, "package-lock.json"), "utf8"));
let licenses = "MySyncFiles editor — bundled third-party licenses\n";
for (const [location, meta] of Object.entries(lock.packages).sort()) {
  if (!location || meta.dev || meta.optional) continue;
  licenses += `\n${location.replace(/^node_modules\//, "")} ${meta.version}\n`;
  licenses += await readFile(path.join(root, location, "LICENSE"), "utf8");
  licenses += "\n";
}
for (const [file, text] of [["editor.js", bundle], ["editor.LICENSE", licenses.trimEnd() + "\n"]]) {
  if (process.argv.includes("--check")) {
    if (await readFile(path.join(root, file), "utf8") !== text) throw new Error(`${file} needs rebuilding`);
  } else {
    const temporary = path.join(root, `.${file}.${process.pid}.tmp`);
    await writeFile(temporary, text);
    await rename(temporary, path.join(root, file));
  }
}
console.log(`Editor bundle verified (${Math.ceil(Buffer.byteLength(bundle) / 1024)} KiB)`);
